import Head from "next/head";
import HeroPages from "../components/layout/HeroPages";
import FeatureCard from "./../components/cards/FeatureCard";
import HeadSection from "./../components/HeadSection";
import { getArticles, getLatestArticles } from "./../services/articleServices";
import { getCategories } from "./../services/categoryServices";
import FetchState from "../components/FetchState";
import ArticlesList from "../components/articles/ArticlesList";
import SubscribeForm from "../components/SubscribeForm";
import CategoriesList from "../components/categories/CategoriesList";
import FeatureSection from "../components/FeatureSection";

export default function Home({
  newArticles,
  articlesVisits,
  categories,
  error,
}) {
  return (
    <>
      <Head>
        <title>موقع مصادر</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <HeroPages
        title="مرحبا بك في موقع مصادر"
        text="هل تبحث عن مكان يحتوي علي الكثير من المصادر والمراجع في الكثير من المجالات التي تهتم بها تجده علي موقع مصادر ويوفر عليك الكثير من البحث وتضيع الوقت في البحث نحن نوفر كل هذا لدينا علي الموقع كل ما عليك فعله البحث في الموقع وسوف تجد كل ماتريده      "
        search={true}
        full={true}
      />

      <FeatureSection />

      {/* start category block */}
      <section className="bg-light py-4">
        <div className="container">
          <HeadSection
            title="الاقسام الموجوده في الموقع"
            text="نحن نوفر اليك الكثير من الاقسام في اغلب المجالات,كل ما عليك فعله هو الدخول الي احدي الاقسام لتجد كل المقالات المتعلقه بهذا القسم"
          />
          <FetchState
            isEmpty={categories.length === 0}
            emptyImage="/writing-room.svg"
            emptyMessage="لا يوجد اقسام في الموقع الان"
            isError={error}
            errorMessage={error}
          >
            <CategoriesList categories={categories} />
          </FetchState>
        </div>
      </section>

      {/* start new Articles block */}
      <section className="bg-light py-4">
        <div className="container">
          <HeadSection
            title="احدث مقالات لدينا"
            text="هنا تجد احدث المقالات التي ضفناها مؤخرا علي الموقع,قم بي تفقدها والقي نظرا عليهم لتجد ما يهمك"
          />
          <FetchState
            isError={error}
            errorMessage={error}
            isEmpty={newArticles.length === 0}
            emptyImage="/online-articles.svg"
            emptyMessage="لا توجد مقالات علي المنصه الان"
          >
            <ArticlesList articles={newArticles} isSlider />
          </FetchState>
        </div>
      </section>

      {/* start articles Visits block */}
      <section className="bg-light py-5">
        <div className="container">
          <HeadSection
            title="اكثر الماقالات مشاهده"
            text="هذه المقالات التي حصلت علي اعلي نسب زياره لدينا وحصلت علي الكثير من الاعجاب لدي الجمهور قم بزيارتها والاستفاده منها"
          />
          <FetchState
            isError={error}
            errorMessage={error}
            isEmpty={articlesVisits.length === 0}
            emptyImage="/online-articles.svg"
            emptyMessage="لا توجد مقالات علي المنصه الان"
          >
            <ArticlesList articles={articlesVisits} isSlider />
          </FetchState>
        </div>
      </section>
      <SubscribeForm />
    </>
  );
}

export async function getStaticProps() {
  try {
    const [categoriesRes, newArticlesRes, articlesVisitsRes] =
      await Promise.all([
        getCategories({ populate: "*" }),
        getLatestArticles(),
        getArticles({ populate: "*" }),
      ]);
    return {
      props: {
        categories: categoriesRes.data || [],
        newArticles: newArticlesRes.data || [],
        articlesVisits: articlesVisitsRes.data || [],
        error: null,
      },
      revalidate: 60,
    };
  } catch (error) {
    return {
      props: {
        newArticles: [],
        articlesVisits: [],
        categories: [],
        error: error?.message || "Failed to fetch data",
      },
      revalidate: 60,  
    };
  }
}
